"
" VIM Configuration
"

" Environment
set undodir=${XDG_CACHE_HOME}/vim
set directory=${XDG_CACHE_HOME}/vim
set backupdir=${XDG_CACHE_HOME}/vim
set viminfo+=n${XDG_CACHE_HOME}/vim/viminfo
set runtimepath=${XDG_CONFIG_HOME}/vim,${XDG_CONFIG_HOME}/vim/after,${XDG_DATA_HOME}/vim,${VIM},${VIMRUNTIME}
let g:netrw_home=$XDG_CACHE_HOME.'/vim'
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

" Plugins
if empty(glob($XDG_DATA_HOME . '/vim/autoload/plug.vim'))
  silent !curl -fLo $XDG_DATA_HOME/vim/autoload/plug.vim --create-dirs 
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin($XDG_DATA_HOME . '/vim/plugged')

Plug 'junegunn/goyo.vim'

call plug#end()

" Encoding
set encoding=utf-8
scriptencoding utf-8

" Color Scheme
colorscheme desert

" Syntax Highlighting
syntax enable               " enable syntax processing
let g:is_bash = 1           " $( ... ) is perfectly fine for POSIX.

" Spaces & Tabs
set tabstop=2               " number of visual spaces per TAB
set shiftwidth=2            " number of spaces per TAB
set softtabstop=2           " number of spaces in TAB when editing
"set expandtab               " tabs are spaces

" UI Config
" set number                  " show line numbers
set showcmd                 " show command in bottom bar
set ruler                   " show ruler in bottom bar
" match ErrorMsg '\%>100v.\+' " highlight lines greater than 100 characters
