#!/bin/sh
#
# lint.sh - consolidated linting before stopping
#
# Called as a Stop hook. Reads the list of files edited during
# the session (tracked by format.sh), groups them by extension,
# and runs the appropriate linters. Also reviews documentation
# files regenerated by docs.sh. Blocks the agent from stopping
# if issues are found or docs were regenerated.

set -u

if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

# Read hook input from stdin.
input="$(cat)"

# Avoid infinite loops: if the agent already continued from a
# previous Stop hook, let it stop this time.
stop_hook_active="$(printf '%s\n' "${input}" | jq -r '.stop_hook_active // false')"
if [ "${stop_hook_active}" = "true" ]; then
  exit 0
fi

session_id="$(printf '%s\n' "${input}" | jq -r '.session_id // empty')"
if [ -z "${session_id}" ]; then
  exit 0
fi

state_dir="${XDG_STATE_HOME:-${HOME}/.local/state}/claude"
state_file="${state_dir}/edited-${session_id}"
docs_state_file="${state_dir}/edited-docs-${session_id}"

# Collect all lint output.
all_output=""

# Process edited files if the state file exists.
if [ -f "${state_file}" ]; then
  # Deduplicate and filter to existing files.
  files="$(sort -u "${state_file}" | sed '/^$/d' | while read -r f; do
    [ -f "${f}" ] && printf '%s\n' "${f}"
  done)"

  # Group files by extension.
  go_files="$(printf '%s\n' "${files}" | grep '\.go$' || true)"
  sh_files="$(printf '%s\n' "${files}" | grep '\.sh$' || true)"

  # Go linting.
  if [ -n "${go_files}" ] && command -v go >/dev/null 2>&1; then
    # Find unique module roots.
    printf '%s\n' "${go_files}" | while read -r f; do
      [ -z "${f}" ] && continue
      dir="$(dirname "${f}")"
      while [ "${dir}" != "/" ]; do
        if [ -f "${dir}/go.mod" ]; then
          printf '%s\n' "${dir}"
          break
        fi
        dir="$(dirname "${dir}")"
      done
    done | sort -u | sed '/^$/d' >/tmp/claude-lint-modules-$$

    # Run go fix and go vet in each module root.
    while read -r root; do
      cd "${root}" && go fix ./... 2>/dev/null
    done </tmp/claude-lint-modules-$$

    while read -r root; do
      output="$(cd "${root}" && go vet ./... 2>&1)"
      if [ -n "${output}" ]; then
        all_output="$(printf '%s\n%s' "${all_output}" "${output}")"
      fi
    done </tmp/claude-lint-modules-$$

    # Run golangci-lint without --fix to catch non-auto-fixable issues.
    if command -v golangci-lint >/dev/null 2>&1; then
      while read -r root; do
        output="$(cd "${root}" && golangci-lint run ./... 2>&1)"
        if [ -n "${output}" ]; then
          all_output="$(printf '%s\n%s' "${all_output}" "${output}")"
        fi
      done </tmp/claude-lint-modules-$$
    fi

    rm -f /tmp/claude-lint-modules-$$
  fi

  # Shell linting.
  if [ -n "${sh_files}" ] && command -v shellcheck >/dev/null 2>&1; then
    output="$(printf '%s\n' "${sh_files}" | xargs shellcheck 2>&1)"
    if [ -n "${output}" ]; then
      all_output="$(printf '%s\n%s' "${all_output}" "${output}")"
    fi
  fi
fi

# Review regenerated documentation.
if [ -f "${docs_state_file}" ]; then
  docs="$(sort -u "${docs_state_file}" | sed '/^$/d' | while read -r f; do
    [ -f "${f}" ] && printf '%s\n' "${f}"
  done)"
  if [ -n "${docs}" ]; then
    all_output="$(printf '%s\n\nNote: The following documentation files were regenerated by hooks:\n%s' "${all_output}" "${docs}")"
  fi
fi

# Strip leading whitespace from output.
all_output="$(printf '%s\n' "${all_output}" | sed '/./,$!d')"

if [ -n "${all_output}" ]; then
  printf '%s\n' "${all_output}" >&2
  exit 2
fi

exit 0
